### PR TITLE
fix: zig 0.12

### LINKED ISSUE #18: `zigmaster` branch doesn't works on `0.12.0-dev.2046+d3a163f86`
branch: `zigmaster`
zig version: `0.12.0-dev.2046+d3a163f86 `

output:
```
/zig/p/122071524b599acc6268eb02f3aaefbb72761276b7ebf05428ab57e6a0551caf312c/build.zig:19:10: error: no field named 'source_file' in struct 'Build.Module.CreateOptions'
        .source_file = .{ .path = "src/main.zig" },
         ^~~~~~~~~~~
/zig/master/lib/std/Build/Module.zig:140:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
referenced by:
    runBuild__anon_15995: /zig/master/lib/std/Build.zig:1851:37
    dependencyInner__anon_14600: /zig/master/lib/std/Build.zig:1831:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/zig/p/12208dc0796bffa6ea9edb60193108e34f835f35fc152e853717aca2b13ba17f3be2/build.zig:9:32: error: no field named 
'source_file' in struct 'Build.Module.CreateOptions'
    _ = b.addModule("xev", .{ .source_file = .{ .path = "src/main.zig" } });
                               ^~~~~~~~~~~
/zig/master/lib/std/Build/Module.zig:140:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
```

PR that fixes it: https://github.com/rsepassi/zigcoro/pull/17

### PR DESCRIPTION
**Pull request by arxdeus**
close #18

### CODE REVIEW

**Comment by rsepassi** [comment]
Great, thank you. Could you update the README as well to specify which version you used?

**Comment by rsepassi** [comment]
Also a local test shows that these still break:

```
zig build test-aio
zig build benchmark
```

**Comment by rsepassi** [comment]
my zig env locally:

```
{
 "zig_exe": "/Users/ryan/zig/0.12.0-dev.2046+d3a163f86/files/zig",
 "lib_dir": "/Users/ryan/zig/0.12.0-dev.2046+d3a163f86/files/lib",
 "std_dir": "/Users/ryan/zig/0.12.0-dev.2046+d3a163f86/files/lib/std",
 "global_cache_dir": "/Users/ryan/.cache/zig",
 "version": "0.12.0-dev.2046+d3a163f86",
 "target": "aarch64-macos.13.5.2...13.5.2-none",
 "env": {
  "ZIG_GLOBAL_CACHE_DIR": null,
  "ZIG_LOCAL_CACHE_DIR": null,
  "ZIG_LIB_DIR": null,
  "ZIG_LIBC": null,
  "ZIG_BUILD_RUNNER": null,
  "ZIG_VERBOSE_LINK": null,
  "ZIG_VERBOSE_CC": null,
  "ZIG_BTRFS_WORKAROUND": null,
  "CC": null,
  "NO_COLOR": null,
  "XDG_CACHE_HOME": null,
  "HOME": "/Users/ryan"
 }
}
```

**Comment by arxdeus** [comment]
@rsepassi added actual version (same as your) + fixed tests, both passed successfully:

```
root# zig build test-aio
root# zig build benchmark
steps [2/5] zig build-exe benchmark ReleaseFast native... LLVM Emit Object... Running benchmark context_switch
steps [3/5] install benchmark... ns/ctxswitch: 12
```

**Comment by rsepassi** [comment]
thanks!
