### ISSUE TITLE
`zigmaster` branch doesn't works on `0.12.0-dev.2046+d3a163f86`

### ISSUE THREAD

**Issue by arxdeus** [rsepassi/zigcoro#18]
branch: `zigmaster`
zig version: `0.12.0-dev.2046+d3a163f86 `

output:
```
/zig/p/122071524b599acc6268eb02f3aaefbb72761276b7ebf05428ab57e6a0551caf312c/build.zig:19:10: error: no field named 'source_file' in struct 'Build.Module.CreateOptions'
        .source_file = .{ .path = "src/main.zig" },
         ^~~~~~~~~~~
/zig/master/lib/std/Build/Module.zig:140:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
referenced by:
    runBuild__anon_15995: /zig/master/lib/std/Build.zig:1851:37
    dependencyInner__anon_14600: /zig/master/lib/std/Build.zig:1831:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/zig/p/12208dc0796bffa6ea9edb60193108e34f835f35fc152e853717aca2b13ba17f3be2/build.zig:9:32: error: no field named 
'source_file' in struct 'Build.Module.CreateOptions'
    _ = b.addModule("xev", .{ .source_file = .{ .path = "src/main.zig" } });
                               ^~~~~~~~~~~
/zig/master/lib/std/Build/Module.zig:140:27: note: struct declared here
pub const CreateOptions = struct {
                          ^~~~~~
```

PR that fixes it: https://github.com/rsepassi/zigcoro/pull/17

**Comment by rsepassi** [comment]
thank you!
